DynCre/Controllers/DataController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

using DynCre.Dal;
using DynCre.Models.DTO;
using DynCre.Utils;

namespace DynCre.Controllers {
    public class DataController: Controller {
        private const string Y_AXIS_ORGVAL = "y-axis-orgVal";
        const string Y_AXIS_IDX = "y-axis-idx";
        private readonly IDataRepository dataRep;

        public DataController(IDataRepository dataRep) {
            this.dataRep = dataRep;
        }

        // GET: Data
        public async Task<ActionResult> Index() {
            ViewBag.Title = "Report page";
            var list = await dataRep.GetAggregatedDataForContractsByCurrentPrincipal();
            return View(list);
        }

        [HttpGet]
        public async Task<JsonResult> ChartData() {
            List<AggregatedChartDataDto> list = await dataRep.GetAggregatedChartData();

            var dtosSorted = list?.OrderBy(t => t.LoanOriginationYear).ThenBy(t => t.SortId).ToList();

            if(!dtosSorted?.Any() ?? true) { return null; }

            List<string> years = dtosSorted.Select(t => $"{t.LoanOriginationYear} - {t.RangeName}").ToList();

            var origVals = dtosSorted.Select(t => t.OriginalPropertyValue).ToList();
            var idxs = dtosSorted.Select(t => t.IndexedLTFV).ToList();

            var texts = dtosSorted.Select(t => new {
                year = $"{t.LoanOriginationYear} - {t.RangeName}",
                text = new List<string> {
                    $"{ReflectionUtils.GetPropertyDisplayName<AggregatedChartDataDto>(i => i.OriginalPrincipalBalance)}: {t.OriginalPrincipalBalance}",
                    $"{ReflectionUtils.GetPropertyDisplayName<AggregatedChartDataDto>(i => i.DebtToIncome)}: {t.DebtToIncome}",
                    $"{ReflectionUtils.GetPropertyDisplayName<AggregatedChartDataDto>(i => i.LoanToIncome)}: {t.LoanToIncome}",
                    $"{ReflectionUtils.GetPropertyDisplayName<AggregatedChartDataDto>(i => i.TotalIncome)}: {t.TotalIncome}",
                    $"{ReflectionUtils.GetPropertyDisplayName<AggregatedChartDataDto>(i => i.IndexedDebtToIncome)}: {t.IndexedDebtToIncome}",
                    $"{ReflectionUtils.GetPropertyDisplayName<AggregatedChartDataDto>(i => i.CurrentInterestRate)}: {t.CurrentInterestRate}",
                    $"{ReflectionUtils.GetPropertyDisplayName<AggregatedChartDataDto>(i => i.OriginalLtv)}: {t.OriginalLtv}",
                    $"{ReflectionUtils.GetPropertyDisplayName<AggregatedChartDataDto>(i => i.OriginalLtfv)}: {t.OriginalLtfv}",
                    $"{ReflectionUtils.GetPropertyDisplayName<AggregatedChartDataDto>(i => i.OriginalForeclosureValue)}: {t.OriginalForeclosureValue}",
                    $"{ReflectionUtils.GetPropertyDisplayName<AggregatedChartDataDto>(i => i.IndexedLTFV)}: {t.IndexedLTFV}",
                    $"{ReflectionUtils.GetPropertyDisplayName<AggregatedChartDataDto>(i => i.OriginalPropertyValue)}: {t.OriginalPropertyValue}",
                }
            }).ToList();

            dynamic data = new {
                chartData = new {
                    labels = years,
                    datasets = new List<dynamic> {
                        new {
                            label = ReflectionUtils.GetPropertyDisplayName<AggregatedChartDataDto>(t => t.OriginalPropertyValue),
                            data = origVals,
                            backgroundColor = "#f00",
                            yAxisID = Y_AXIS_ORGVAL,
                        },
                        new {
                            label = ReflectionUtils.GetPropertyDisplayName<AggregatedChartDataDto>(t => t.IndexedLTFV),
                            data = idxs,
                            backgroundColor = "#00f",
                            yAxisID = Y_AXIS_IDX
                        }
                    }
                },
                options = new {
                    scales = new {
                        yAxes = new List<dynamic>() {
                            new {
                                position = "left",
                                id = Y_AXIS_ORGVAL
                            },
                            new {
                                position = "right",
                                id = Y_AXIS_IDX
                            }
                        }
                    }
                },
                tooltips = texts
            };

            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

DynCre/Controllers/HomeController.cs
using System.Threading.Tasks;
using System.Web.Mvc;

using DynCre.Dal;
using DynCre.Services;

namespace DynCre.Controllers {
    public class HomeController: Controller {
        private readonly IDataRepository dataRep;
        private readonly ITestDataGenerator generator;

        public HomeController(ITestDataGenerator generator, IDataRepository dataRep) {
            this.generator = generator;
            this.dataRep = dataRep;
        }

        public ActionResult Index() {
            return View();
        }

        public ActionResult About() {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact() {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public async Task<ActionResult> Generate() {
            var result = await generator.ScaleData(3);
            // to scale it up to 4kk uncomment following line
            //var result = await generator.ScaleData(4000);
            if(!result) { return View("Error"); }
            return View("Index");
        }

        public async Task<ActionResult> Prepare() {
            bool result = await dataRep.PrepareData();
            if(!result) { return View("Error"); }
            return View("Index");
        }
    }
}

DynCre/Views/Data/Index.cshtml
@model IEnumerable<DynCre.Models.DTO.AggregatedDataDto>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
<div id="containerForData">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.RangeName)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.TotalRecordsCount)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.OriginalPrincipalBalance)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.DebtToIncome)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.LoanToIncome)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.TotalIncome)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.IndexedDebtToIncome)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.IndexedLoanToIncome)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.CurrentInterestRate)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.OriginalLtv)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.OriginalLtfv)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.OriginalForeclosureValue)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.IndexedLTFV)
            </th>
        </tr>
        </thead>
        <tbody>
        @foreach(var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RangeName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalRecordsCount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OriginalPrincipalBalance)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DebtToIncome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LoanToIncome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalIncome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IndexedDebtToIncome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IndexedLoanToIncome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrentInterestRate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OriginalLtv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OriginalLtfv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OriginalForeclosureValue)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IndexedLTFV)
                </td>
            </tr>
        }
        </tbody>
    </table>
    <canvas id="reportChart"></canvas>
</div>

<div class="print-exclude">
    <input type="button" class="btn btn-default" onclick="printDiv('containerForData')" value="Print this page"/>
    <script type="text/javascript">
        buildChart();
    </script>
</div>

DynCre/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Test assignement Dynamic Credit Georgy Grigoryev</h1>
    <p class="lead">
        Project based on the attached dataset (Test_Scenario) which includes:
        <ul>

            <li>1000 rows per table [please scale/multiply it up to 4 million rows at your end]</li>
            <li>Normalized data structure (you can adjust the DB structure as needed for performance improvement)(</li>

        </ul>
    </p>
    @Html.ActionLink("Go to page with data", "Index", "Data")
</div>

<div class="row">
    <div class="col-md-4">


        <h2>Prepare data</h2>
        <p>Data is loaded in the background. When all files from source folder is loaded please press the button to prepare data for the report</p>
        @Html.ActionLink("Let's go", "Prepare", "Home", null, new {
            @class = "btn btn-default"
        })
    </div>
    <div class="col-md-4">

        <h2>Scale data</h2>
        <p>
            When you press this button application will scale loaded data 4000x times. If we have 1000 rows in Contracts it will be scaled to 4 millions.
        </p>
        @Html.ActionLink("Let's go", "Generate", "Home", null, new {
            @class = "btn btn-default"
        })

    </div>
</div>

DynCre/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Dynamic Credit Georgy Grigoryev</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/print")
    @Scripts.Render("~/bundles/chartjs")
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Dynamic Credit", "Index", "Home", new {
                area = ""
            }, new {
                @class = "navbar-brand"
            })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Report", "Index", "Data")</li>
            </ul>
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Dynamic Credit Georgy Grigoryev</p>
    </footer>
</div>

@RenderSection("scripts", required: false)
</body>
</html>